### ISSUE TITLE
Crash trying to run locally

### ISSUE THREAD

**Issue by ghost** [jamesward/salesforce-webhook-creator#23]
When I try to run locally I get the following crash when I try to navigate to the listening http server.

```
#sbt run
[info] Loading project definition from /home/betterlesson/crap/salesforce-webhook-creator/project
[info] Set current project to salesforce-webhook-creator (in build file:/home/betterlesson/crap/salesforce-webhook-creator/)
[info] Updating {file:/home/betterlesson/crap/salesforce-webhook-creator/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 15 Scala sources and 1 Java source to /home/betterlesson/crap/salesforce-webhook-creator/target/scala-2.11/classes...
[info] JavaScript linting on 1 source(s)
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
java.lang.NoClassDefFoundError: Could not initialize class play.api.http.DefaultHttpErrorHandler$
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
	at play.core.server.Server$class.getHandlerFor(Server.scala:65)
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
```

**Comment by jamesward** [comment]
For some reason the real error is being hidden.  This is probably due to missing env vars: `FORCE_CONSUMER_KEY` and `FORCE_CONSUMER_SECRET`

Let me know if setting those fixes this.

**Comment by ghost** [comment]
@jamesward  that was it running
```
 FORCE_CONSUMER_KEY=true FORCE_CONSUMER_SECRET=true sbt run
```
resolved my issue

**Comment by ghost** [comment]
when i click either button in the app i see the following error from salesforce

```
error=invalid_client_id&error_description=client%20identifier%20invalid
```

the url it directed me to is 
```
https://test.salesforce.com/services/oauth2/authorize?response_type=code&client_id=true&redirect_uri=http://localhost:9000/_oauth_callback&state=sandbox
```

**Comment by jamesward** [comment]
Those values need to be set to the ones from a Salesforce Connected App.

**Comment by ghost** [comment]
sorry i thought you meant i needed to set those to true not that they needed to be the correct vars from my conf. works now thanks.
